# -*- coding: utf-8 -*-
"""Analise_otimizacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPaNaHfGPW14DoXWzIlVt_X4ZL-zSUAH
"""

#Importando as bibliotecas
import pandas as pd #data manipulation
import matplotlib.pyplot as plt #plotting library

#Habilitando a abertura de dados que estão no Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Abrir Tabela demandas atualizada
Otimizacao_at = pd.read_csv('/content/drive/My Drive/Dados_API/Otimizacao_at.csv')

print(Otimizacao_at)

import pandas as pd
import matplotlib.pyplot as plt

# Supondo que seu dataframe já esteja carregado como "Otimizacao_at"
# Exemplo de dataframe
# Otimizacao_at = pd.read_csv('caminho_para_seu_arquivo.csv')

# Somando todas as linhas de cada coluna
total_custo_rota = Otimizacao_at['Custo_rota'].sum()
total_custo_rota_otim2023 = Otimizacao_at['Custo_rota_otim2023'].sum()
total_custo_rota_otim2024 = Otimizacao_at['Custo_rota_otim2024'].sum()

# Preparando os dados para o gráfico
data = {
    'Custo_rota': total_custo_rota,
    'Custo_rota_otim2023': total_custo_rota_otim2023,
    'Custo_rota_otim2024': total_custo_rota_otim2024
}

# Criando o gráfico
fig, ax = plt.subplots()
bars = ax.bar(data.keys(), data.values())

# Adicionando os valores acima das barras
for bar in bars:
    height = bar.get_height()
    ax.text(
        bar.get_x() + bar.get_width() / 2.0,
        height,
        f'{height:.2f}',
        ha='center',
        va='bottom'
    )

# Configurando rótulos e título
ax.set_ylabel('Total Custo')
ax.set_title('Comparação dos Custos das Rotas')

# Exibindo o gráfico
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Supondo que seu dataframe já esteja carregado como "Otimizacao_at"
# Exemplo de dataframe
# Otimizacao_at = pd.read_csv('caminho_para_seu_arquivo.csv')

# Agrupar por 'CO.Fabrica' e somar os custos
grouped_data = Otimizacao_at.groupby('CO.Fabrica').sum()

# Preparando os dados para o gráfico
fabricas = grouped_data.index
custo_rota = grouped_data['Custo_rota']
custo_rota_otim2023 = grouped_data['Custo_rota_otim2023']
custo_rota_otim2024 = grouped_data['Custo_rota_otim2024']

# Criando o gráfico
fig, ax = plt.subplots(figsize=(10, 6))

# Definindo a largura das barras e a posição
bar_width = 0.25
bar_positions = range(len(fabricas))

# Plotando as barras
bars1 = ax.bar(bar_positions, custo_rota, bar_width, label='Custo Rota')
bars2 = ax.bar([p + bar_width for p in bar_positions], custo_rota_otim2023, bar_width, label='Custo Rota Otim 2023')
bars3 = ax.bar([p + bar_width * 2 for p in bar_positions], custo_rota_otim2024, bar_width, label='Custo Rota Otim 2024')

# Adicionando os valores acima das barras
for bars in [bars1, bars2, bars3]:
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            height,
            f'{height:.2f}',
            ha='center',
            va='bottom'
        )

# Configurações do gráfico
ax.set_xlabel('Fábricas')
ax.set_ylabel('Total Custo')
ax.set_title('Comparação dos Custos das Rotas por Fábrica')
ax.set_xticks([p + bar_width for p in bar_positions])
ax.set_xticklabels(fabricas, rotation=45)
ax.legend()

# Exibindo o gráfico
plt.tight_layout()
plt.show()